### ISSUE TITLE
can we make lunch recipe more fun with emojis?

### ISSUE THREAD

**Issue by gomesthalita** [IntroToCode/Spring22_Recipes_Codemates9#10]
## 💬 Discussion topic

Text

## ❗ Potential issues

Text

## 👥 People to consult

Text

## 📃 Details

Text

**Comment by Soohwan617** [comment]
Yes, if we use emojis for each ingredients, it would be nice

**Comment by gujuletap2** [comment]
good idea, let's add in some more emoji's.
