### ISSUE TITLE
Correct ingredients

### ISSUE THREAD

**Issue by gujuletap2** [IntroToCode/Spring22_Recipes_Codemates9#2]
## 💬 Discussion topic

Correct ingredients 

## ❗ Potential issues

Do we think we have the correct list of ingredient's for our pancake recipe?

## 👥 People to consult

@kellyychu @gomesthalita @Soohwan617 

## 📃 Details

Are we missing anything to make the pancakes even tastier?

**Comment by gomesthalita** [comment]
Ok, already did the merge

**Comment by kellyychu** [comment]
Looks good to me
