### ISSUE TITLE
Creating a lunch option for those with dietary restrictions

### ISSUE THREAD

**Issue by kellyychu** [IntroToCode/Spring22_Recipes_Codemates9#4]
## 💬 Discussion topic

I think this is a great recipe but some people may have dietary restrictions like being vegetarian. 

## ❗ Potential issues

Should we include vegetarian/vegan friendly options like getting tofu instead of meat?

## 👥 People to consult

@gomesthalita @alefiyahb @Soohwan617 @gujuletap2 

## 📃 Details

Proposing we can create an option with tofu instead of meat

**Comment by Soohwan617** [comment]
It is really thoughtful consideration in a preparation of lunch option. I would agree with you

**Comment by gujuletap2** [comment]
Yes, very good thought, I agree as well!
