### ISSUE TITLE
Breakfast - salt ingredient

### ISSUE THREAD

**Issue by kellyychu** [IntroToCode/Spring22_Recipes_Codemates9#7]
## 💬 Discussion topic

Salt is listed twice in the ingredients for the breakfast recipe

## ❗ Potential issues

Can we clarify how salt should be used in the ingredients so it doesn't look confusing?

## 👥 People to consult

@gomesthalita @Soohwan617 @alefiyahb @gujuletap2

**Comment by alefiyahb** [comment]
1 tablespoon of salt
